BOOTLOADER = atmel-dfu

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

RGB_MATRIX_ENABLE = yes

MOUSEKEY_ENABLE = no

TAP_DANCE_ENABLE = yes

STENO_ENABLE = yes

# Space saving options
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no